//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Emails", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک تأیید ایمیل جایگزین جهت دریافت ایمیل از شبکه اجتماعی vKurdistan.
        /// </summary>
        internal static string AltEmailActivationCodeLink {
            get {
                return ResourceManager.GetString("AltEmailActivationCodeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سلام
        ///&lt;br /&gt;
        ///این ایمیل جهت تأیید ایمیل جایگزین در شبکه اجتماعی vKurdistan و به درخواست.
        /// </summary>
        internal static string AltEmailActivationCodePhrase1 {
            get {
                return ResourceManager.GetString("AltEmailActivationCodePhrase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شده است، جهت تأیید و تغییر ایمیل جایگزین بر روی لینک زیر کلیک کنید.
        ///&lt;br /&gt;
        ///توجه: در صورتی که این ایمیل به درخواست شما ارسال نشده است، از کلیک بر روی لینک زیر جداً خودداری فرمایید..
        /// </summary>
        internal static string AltEmailActivationCodePhrase2 {
            get {
                return ResourceManager.GetString("AltEmailActivationCodePhrase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید ایمیل جایگزین.
        /// </summary>
        internal static string AlternatveEmailActivationSubject {
            get {
                return ResourceManager.GetString("AlternatveEmailActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  با سپاس
        ///&lt;br /&gt;
        ///تیم برنامه نویسی vKurdistan
        ///&lt;/div&gt;.
        /// </summary>
        internal static string EmailsFooter {
            get {
                return ResourceManager.GetString("EmailsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامی از vKurdistan.
        /// </summary>
        internal static string EmailsTitle {
            get {
                return ResourceManager.GetString("EmailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات ارسال شده برای مطالب شما.
        /// </summary>
        internal static string EnotCommentsCount {
            get {
                return ResourceManager.GetString("EnotCommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های دوستی جدید.
        /// </summary>
        internal static string ENotFriendshipRequestsCount {
            get {
                return ResourceManager.GetString("ENotFriendshipRequestsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شبکه اجتماعی vKurdistan
        ///&lt;br /&gt;
        ///در زمانی که شما در شبکه حضور نداشته اید برای شما اتفاق جدیدی افتاده است، برای کسب اطلاع از این اتفاقات به حساب کاربری خود وارد شده و آگاه سازهای مربوطه را مشاهده نمایید.
        ///&lt;br /&gt;
        ///برای ورود به حساب کاربری خود بر روی لینک زیر کلیک کنید:
        ///&lt;br /&gt;.
        /// </summary>
        internal static string ENotificationContentPart1 {
            get {
                return ResourceManager.GetString("ENotificationContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vKurdistan | آگاه ساز.
        /// </summary>
        internal static string ENotificationSubject {
            get {
                return ResourceManager.GetString("ENotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسندهای جدید برای مطالب شما.
        /// </summary>
        internal static string EnotLikesCount {
            get {
                return ResourceManager.GetString("EnotLikesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های جدید خوانده نشده.
        /// </summary>
        internal static string EnotNewMessagesCount {
            get {
                return ResourceManager.GetString("EnotNewMessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب به اشتراک گذاشته شده شما.
        /// </summary>
        internal static string EnotSharesCount {
            get {
                return ResourceManager.GetString("EnotSharesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته های جدید روی دیوار شما.
        /// </summary>
        internal static string EnotWallPostsCount {
            get {
                return ResourceManager.GetString("EnotWallPostsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شبکه اجتماعی vKurdistan،
        ///&lt;br /&gt;
        ///با سلام،
        ///&lt;br /&gt;
        ///نام کاربری و گذرواژه حساب کاربری ایجاد شده برای شما بشرح زیر است:
        ///&lt;br /&gt;.
        /// </summary>
        internal static string GeneratedPasswordEmailPart1 {
            get {
                return ResourceManager.GetString("GeneratedPasswordEmailPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ورود به حساب کاربری خود بر روی لینک زیر کلیک کنید:.
        /// </summary>
        internal static string GeneratedPasswordEmailPart2 {
            get {
                return ResourceManager.GetString("GeneratedPasswordEmailPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه حساب کاربری.
        /// </summary>
        internal static string GeneratedPasswordSubject {
            get {
                return ResourceManager.GetString("GeneratedPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد حساب کاربری خود شوید.
        /// </summary>
        internal static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شبکه اجتماعی vKurdistan،
        ///&lt;br /&gt;
        ///با سلام،
        ///&lt;br /&gt;
        ///گذرواژه حساب کاربری شما بدرخواست شما ارسال گردیده و بشرح زیر است:
        ///&lt;br /&gt;.
        /// </summary>
        internal static string PasswordRecoveryEmail {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vKurdistan | بازیافت گذرواژه.
        /// </summary>
        internal static string PasswordRecoverySubject {
            get {
                return ResourceManager.GetString("PasswordRecoverySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک فعالسازی حساب کاربری.
        /// </summary>
        internal static string RegisterationCodeLink {
            get {
                return ResourceManager.GetString("RegisterationCodeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شبکه اجتماعی vKurdistan،
        ///&lt;br /&gt;
        ///با سلام،
        ///&lt;br /&gt;
        ///کد فعالسازی حساب کاربری شما کد زیر است:
        ///&lt;br /&gt;
        ///کد فعالسازی: .
        /// </summary>
        internal static string RegisterationCodePhrase1 {
            get {
                return ResourceManager.GetString("RegisterationCodePhrase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///همچنین می توانید با کلیک بر روی لینک زیر نسبت به فعالسازی حساب کاربری خود اقدام نمایید:
        ///&lt;br /&gt;.
        /// </summary>
        internal static string RegisterationCodePhrase2 {
            get {
                return ResourceManager.GetString("RegisterationCodePhrase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vKurdistan | کد فعالسازی حساب.
        /// </summary>
        internal static string RegisterationCodeSubject {
            get {
                return ResourceManager.GetString("RegisterationCodeSubject", resourceCulture);
            }
        }
    }
}
