//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی جهت ادامه باید وارد سایت شوید، چنانچه دارای حساب کاربری در vKurdistan نیستید،
        ///&lt;a href=&quot;/account/register&quot;&gt;ثبت نام کنید.&lt;/a&gt;.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز لازم برای دسترسی به این قسمت را ندارید.
        ///چنانچه دارای حساب کاربری در vKurdistan نیستید،
        ///&lt;a href=&quot;/account/register&quot;&gt;ثبت نام کنید.&lt;/a&gt;.
        /// </summary>
        internal static string AccessDeniedForObjects {
            get {
                return ResourceManager.GetString("AccessDeniedForObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالسازی وارد شده صحیح نیست، لطفاً دوباره بررسی کنید و یا از طریق لینک فعالسازی ارسال شده به ایمیل خود اقدام نمایید..
        /// </summary>
        internal static string ActivationCodeIsIncorrect {
            get {
                return ResourceManager.GetString("ActivationCodeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده یا کد فعالسازی نامعتبر است، لطفاً دوباره بررسی نمایید..
        /// </summary>
        internal static string ActivationNotValidEmailOrCode {
            get {
                return ResourceManager.GetString("ActivationNotValidEmailOrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما با موفقیت فعال گردید، از هم اکنون می توانید 
        ///&lt;a href=&quot;/account/login&quot;&gt;وارد حساب کاربری خود شوید.&lt;/a&gt;&lt;br /&gt;به vKurdistan خوش آمدید!.
        /// </summary>
        internal static string ActivationSuccess {
            get {
                return ResourceManager.GetString("ActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری با ایمیل وارد شده قبلاً فعال شده و نیازی به فعالسازی مجدد نیست..
        /// </summary>
        internal static string ActivationUserIsCurrentlyActive {
            get {
                return ResourceManager.GetString("ActivationUserIsCurrentlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در ارتباط با سرور رخ داده است.
        /// </summary>
        internal static string AjaxFail {
            get {
                return ResourceManager.GetString("AjaxFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده قبلاً انتخاب شده است، لطفاً نام دیگری وارد نمایید..
        /// </summary>
        internal static string AliasExists {
            get {
                return ResourceManager.GetString("AliasExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفانه کد فعالسازی ایمیل جایگزین اشتباه می باشد، لطفاً به ایمیل خود وارد شده و بر روی لینک مربوطه کلیک کنید.
        ///&lt;br /&gt;
        ///در صورت تکرار این پیام، به حساب کاربری خود وارد شوید و نسبت به ارسال مجدد کد فعالسازی اقدام نمایید..
        /// </summary>
        internal static string AltEmailActivationCodeIncorrect {
            get {
                return ResourceManager.GetString("AltEmailActivationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده یا کد فعالسازی نامعتبر است، لطفاً دوباره بررسی نمایید..
        /// </summary>
        internal static string AltEmailActivationNotValidEmailOrCode {
            get {
                return ResourceManager.GetString("AltEmailActivationNotValidEmailOrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالسازی ایمیل جایگزین با موفقیت انجام شد.
        ///&lt;br /&gt;
        ///از این پس ایمیلهای آگاه ساز و سایر ایمیل ها از طرف شبکه اجتماعی vKurdistan به این ایمیل ارسال خواهند شد.
        ///&lt;br /&gt;
        ///توجه: شما برای ورود به سایت همچنان از ایمیل اصلی خود به عنوان نام کاربری استفاده خواهید کرد..
        /// </summary>
        internal static string AltEmailActivationSuccess {
            get {
                return ResourceManager.GetString("AltEmailActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیلی حاوی لینک فعالسازی به ایمیل جایگزین تعریف شده فرستاده شد، جهت فعال شدن باید به ایمیل خود مراجعه و بر روی لینک فعالسازی کلیک کنید..
        /// </summary>
        internal static string AltEmailShouldBeActivated {
            get {
                return ResourceManager.GetString("AltEmailShouldBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید؟.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با آپلودگر فایل مشکل دارید؟ جهت استفاده از نسخه ساده شده کلیک کنید..
        /// </summary>
        internal static string BasicHtmlUploader {
            get {
                return ResourceManager.GetString("BasicHtmlUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار آدرس ایمیل صحیح نیست.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما با موفقیت برای حذف برنامه ریزی و شما از حساب خود خارج شدید، تا مدت 30 روز برای جلوگیری از حذف دائم حسابتان فرصت دارید، در صورن عدم ورود به حساب کاربری در این مدت حساب کاربریتان برای همیشه حذف خواهد شد..
        /// </summary>
        internal static string DeleteAccountSuccessMEssage {
            get {
                return ResourceManager.GetString("DeleteAccountSuccessMEssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز دسترسی لازم نیستید..
        /// </summary>
        internal static string DontHaveAccess {
            get {
                return ResourceManager.GetString("DontHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی جهت نمایش یافت نشد..
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفانه شما حداکثر تعداد آلبوم های مجاز را ایجاد نموده اید و نمی توانید آلبوم جدیدی اضافه کنید..
        /// </summary>
        internal static string ExceedMaxAlbums {
            get {
                return ResourceManager.GetString("ExceedMaxAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفیم، شما در هر پست حداکثر می توانید 3 تصویر ارسال نمایید..
        /// </summary>
        internal static string ExceedMaxPostPhotos {
            get {
                return ResourceManager.GetString("ExceedMaxPostPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در یک پست می توانید فقط یک فایل ویدئویی ارسال نمایید..
        /// </summary>
        internal static string ExceedMaxPostVideos {
            get {
                return ResourceManager.GetString("ExceedMaxPostVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در عملیات رخ داده است، لطفاً مجدداً سعی کنید..
        /// </summary>
        internal static string ExceptionTryAgain {
            get {
                return ResourceManager.GetString("ExceptionTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در ارتباط با حساب کاربری فیسبوک شما رخ داده است، لطفاً مجدداً تلاش کنید..
        /// </summary>
        internal static string FacebookConnectErrorMessage {
            get {
                return ResourceManager.GetString("FacebookConnectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با فیسبوک با موفقیت انجام شد، از این پس می توانید با حساب کاربری فیسبوک خود وارد سایت شوید، همچنین گذرواژه حساب کاربری شما در vKurdistan به ایمیل اعلام شده در فیسبوکتان ارسال گردید..
        /// </summary>
        internal static string FacebookConnectSuccessfullMessageForAnonymous {
            get {
                return ResourceManager.GetString("FacebookConnectSuccessfullMessageForAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با فیسبوک با موفقیت انجام شد، از این پس می توانید با حساب کاربری فیسبوک خود نیز وارد سایت شوید..
        /// </summary>
        internal static string FacebookConnectSuccessfullMessageForAuthenticated {
            get {
                return ResourceManager.GetString("FacebookConnectSuccessfullMessageForAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش یک خطای غیر منتظره رخ داده است، لطفاً از طریق 
        ///&lt;a href=&quot;/account/connecttofacebook?step=1&quot;&gt;این لینک&lt;/a&gt; مجدداً سعی کنید..
        /// </summary>
        internal static string FacebookConnectUnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("FacebookConnectUnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اطلاعات مربوط به ارتباط حساب فیسبوکی شما یافت نشد، لطفاً از طریق لینک زیر از برقراری ارتباط حساب کاربری خود با فیسبوک اطمینان حاصل کنید:
        ///&lt;br /&gt;
        ///&lt;a href=&quot;/account/connecttofacebook&quot;&gt;ارتباط با فیسبوک&lt;/a&gt;.
        /// </summary>
        internal static string FacebookLoginConnectionNotExists {
            get {
                return ResourceManager.GetString("FacebookLoginConnectionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت در فیسبوک به اشتراک گذاشته شد..
        /// </summary>
        internal static string FacebookShareSuccessfullMessage {
            get {
                return ResourceManager.GetString("FacebookShareSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک درخواست دوستی پاسخ داده نشده بین شما وجود دارد، شما قادر به ارسال درخواست دوستی جدید نمی باشید..
        /// </summary>
        internal static string FriendshipRequestExists {
            get {
                return ResourceManager.GetString("FriendshipRequestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلاً این مورد را به اشتراگ گذاشته اید، مجاز به اشتراک دوباره نیستید..
        /// </summary>
        internal static string HasSharedBefore {
            get {
                return ResourceManager.GetString("HasSharedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت گذرواژه وارد شده صحیح نیست&lt;br /&gt;لطفاً به راهنمای کنار تکست باکس توجه کنید.
        /// </summary>
        internal static string IncorectPassword {
            get {
                return ResourceManager.GetString("IncorectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ارسالی شما از حداکثر اندازه مجاز قابل ارسال تجاوز کرده است.
        /// </summary>
        internal static string LargerThanMaximumUpload {
            get {
                return ResourceManager.GetString("LargerThanMaximumUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا(ها)ی زیر رخ داده است:.
        /// </summary>
        internal static string ListOfErrorsTitle {
            get {
                return ResourceManager.GetString("ListOfErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، حساب کاربری شما توسط مدیران سایت مسدود شده است، جهت اطلاع از علت مسدودسازی و یا درخواست رفع انسداد با مدیریت تماس بگیرید..
        /// </summary>
        internal static string LoginBlockedAccount {
            get {
                return ResourceManager.GetString("LoginBlockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، حساب کاربری شما حذف شده است، با توجه به اینکه در مدت زمان مجاز برای بازیافت وارد حساب کاربریتان نشده اید، جهت بازیافت و فعالسازی مجدد حساب کاربریتان از طریق
        ///&lt;a href=&quot;/Pages/ContactUs&quot;&gt;این صفحه&lt;/a&gt; با مدیریت تماس بگیرید..
        /// </summary>
        internal static string LoginDeletedAccount {
            get {
                return ResourceManager.GetString("LoginDeletedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل و یا گذرواژه وارد شده معتبر نیست، لطفاً به موارد زیر توجه کنید:
        ///&lt;br /&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;دقت نمایید که ایمیل وارد شده دارای فرمت صحیح باشد، مثال: xyz@vkurdistan.com&lt;/li&gt;
        ///&lt;li&gt;گذرواژه شما می بایست دارای شرایط ذکر شده صفحه ثبت نام باشد&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string LoginNotValidAttempt {
            get {
                return ResourceManager.GetString("LoginNotValidAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی حساب کاربری شما بدلیل مسائل امنیتی موقتاً مسدود شده است، پس از مدت زمانی کوتاه می توانید دوباره تلاش کنید.
        /// </summary>
        internal static string LoginUserLockedOut {
            get {
                return ResourceManager.GetString("LoginUserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما فعال نگردیده است، لطفاً یکی از موارد زیر را انجام دهید:
        ///&lt;br /&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;به ایمیل خود مراجعه کرده و بر روی لینک فعالسازی حساب کاربری کلیک کنید، دقت کنید ممکن است ایمیل فعالسازی در پوشه spam قرار گرفته باشد&lt;/li&gt;
        ///&lt;li&gt;برای ارسال مجدد لینک فعالسازی &lt;a href=&quot;/account/activation&quot;&gt;به این صفحه&lt;/a&gt; مراجعه کنید&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string LoginUserNotApproved {
            get {
                return ResourceManager.GetString("LoginUserNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده صحیح نمی باشد، کاربری با این آدرس ایمیل وجود ندارد.
        /// </summary>
        internal static string LoginUserNotExists {
            get {
                return ResourceManager.GetString("LoginUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی گذرواژه وارد شده صحیح نیست، دقت کنید در صورت تکرار بیش از حد مجاز، حساب کاربریتان برای جلوگیری از دسترسی غیر مجاز موقتا مسدود خواهد شد.
        /// </summary>
        internal static string LoginWrongPassword {
            get {
                return ResourceManager.GetString("LoginWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ارسال شد..
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست دوستی جدیدی ندارید..
        /// </summary>
        internal static string NoNewRequest {
            get {
                return ResourceManager.GetString("NoNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعیه ای موجود نیست..
        /// </summary>
        internal static string NoNotification {
            get {
                return ResourceManager.GetString("NoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کننده ای برای پیام مشخص نکرده اید..
        /// </summary>
        internal static string NoRecieverForMessage {
            get {
                return ResourceManager.GetString("NoRecieverForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به دنبال کردن این کاربر نیستید..
        /// </summary>
        internal static string NotAllowedToFollow {
            get {
                return ResourceManager.GetString("NotAllowedToFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به ارسال نظر برای این مطلب نیستید..
        /// </summary>
        internal static string NotAllowedToLeaveComment {
            get {
                return ResourceManager.GetString("NotAllowedToLeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به ارسال پست روی دیوار این کاربر نمی باشید..
        /// </summary>
        internal static string NotAllowedToPostOnWall {
            get {
                return ResourceManager.GetString("NotAllowedToPostOnWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ارسال درخواست دوستی به این کاربر را ندارید..
        /// </summary>
        internal static string NotAllowedToSendFriendshipRequest {
            get {
                return ResourceManager.GetString("NotAllowedToSendFriendshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ارسال پیام به این کاربر را ندارید..
        /// </summary>
        internal static string NotAllowedToSendMessage {
            get {
                return ResourceManager.GetString("NotAllowedToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده معتبر نیست، لطفاً بررسی کرده و مجدداً اقدام کنید..
        /// </summary>
        internal static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل اعلام شده از طرف فیسبوک صحیح نمی باشد، لطفاً مجدداً سعی کنید.
        ///&lt;br /&gt;
        ///توجه: در صورتی که از طریق شماره تلفن در فیسبوک ثبت نام کرده اید، قادر به برقراری ارتباط نخواهیم بود، در این صورت
        ///&lt;a href=&quot;/account/register&quot;&gt;لطفاً در شبکه اجتماعی vKurdistan ثبت نام کنید.&lt;/a&gt;.
        /// </summary>
        internal static string NotValidFacebookEmail {
            get {
                return ResourceManager.GetString("NotValidFacebookEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در دریافت اطلاعات شما از فیسبوک رخ داده است، لطفاً مجدداً سعی کنید..
        /// </summary>
        internal static string NotValidFacebookInformation {
            get {
                return ResourceManager.GetString("NotValidFacebookInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل انتخابی شما صحیح نیست..
        /// </summary>
        internal static string NotValidFileFormat {
            get {
                return ResourceManager.GetString("NotValidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل انتخابی شما صحیح نیست، تنها می توانید فایلی با یکی از فرمت های زیر ارسال نمایید:
        ///&lt;br /&gt;
        ///jpg, png, gif.
        /// </summary>
        internal static string NotValidPhotoFormat {
            get {
                return ResourceManager.GetString("NotValidPhotoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل انتخابی شما صحیح نیست، تنها می توانید فایلی با یکی از فرمت های زیر ارسال نمایید:
        ///&lt;br /&gt;
        ///mp4, mpeg, mov, flv, avi.
        /// </summary>
        internal static string NotValidVideoFormat {
            get {
                return ResourceManager.GetString("NotValidVideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام خوانده نشده ای ندارید.
        /// </summary>
        internal static string NoUnreadMessages {
            get {
                return ResourceManager.GetString("NoUnreadMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه قدیمی شما صحیح نمی باشد..
        /// </summary>
        internal static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مورد نظر شما یافت نشد.
        ///&lt;br /&gt;
        ///شما ممکن است نتوانید این صفحه را به دلایل زیر ببینید:
        ///&lt;ul&gt;
        ///&lt;li&gt;
        ///آدرس وب سایت را اشتباهی وارد کردید.
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///موتور جست و جویی که استفاده می کنید یک لیست خارج از تاریخ از این وب سایت دارد.
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///تاریخ بوک مارک شما درست نباشد.
        ///&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string PageNotFoundErrorText {
            get {
                return ResourceManager.GetString("PageNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول گذرواژه: 8 &lt;br /&gt;حداقل تعداد حروف: 1&lt;br /&gt;حداقل تعداد رقم: 1.
        /// </summary>
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه شما به ایمیلتان ارسال شد، لطفاً به ایمیل خود مراجعه کنید.
        ///&lt;br /&gt;
        ///(توجه: ممکن است ایمیل ارسالی در پوشه spam قرار گرفته باشد.).
        /// </summary>
        internal static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای قد صحیح نمی باشد.
        /// </summary>
        internal static string RangeHeight {
            get {
                return ResourceManager.GetString("RangeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای وضعیت تأهل صحیح نمی باشد.
        /// </summary>
        internal static string RangeMaritalStatus {
            get {
                return ResourceManager.GetString("RangeMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای وزن صحیح نمی باشد.
        /// </summary>
        internal static string RangeWeight {
            get {
                return ResourceManager.GetString("RangeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده صحیح نمی باشد..
        /// </summary>
        internal static string RegularExpressionAlias {
            get {
                return ResourceManager.GetString("RegularExpressionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده صحیح نمی باشد..
        /// </summary>
        internal static string RegularExpressionEmail {
            get {
                return ResourceManager.GetString("RegularExpressionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی وارد شده دارای فرمت قابل قبول نمی باشد..
        /// </summary>
        internal static string RegularExpressionFullName {
            get {
                return ResourceManager.GetString("RegularExpressionFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه وارد شده صحیح نمی باشد..
        /// </summary>
        internal static string RegularExpressionMobNumber {
            get {
                return ResourceManager.GetString("RegularExpressionMobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه صفحه را بصورت صحیح وارد کنید..
        /// </summary>
        internal static string RegularExpressionPageName {
            get {
                return ResourceManager.GetString("RegularExpressionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرداخت هزینه را مشخص نمایید..
        /// </summary>
        internal static string RequiredAdvPaymentStatus {
            get {
                return ResourceManager.GetString("RequiredAdvPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تبلیغات را انتخاب نمایید..
        /// </summary>
        internal static string RequiredAdvType {
            get {
                return ResourceManager.GetString("RequiredAdvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام آلبوم را وارد کنید.
        /// </summary>
        internal static string RequiredAlbumName {
            get {
                return ResourceManager.GetString("RequiredAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام کاربری وارد نشده است..
        /// </summary>
        internal static string RequiredAlias {
            get {
                return ResourceManager.GetString("RequiredAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع را انتخاب نمایید..
        /// </summary>
        internal static string RequiredBeginDate {
            get {
                return ResourceManager.GetString("RequiredBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً روز تولد خود را مشخص نمایید.
        /// </summary>
        internal static string RequiredBirthDay {
            get {
                return ResourceManager.GetString("RequiredBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ارسالی شما خالی است، متنی برای نظر خود وارد نمایید..
        /// </summary>
        internal static string RequiredCommentText {
            get {
                return ResourceManager.GetString("RequiredCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوایی وارد نمایید..
        /// </summary>
        internal static string RequiredContent {
            get {
                return ResourceManager.GetString("RequiredContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان هزینه را مشخص نمایید..
        /// </summary>
        internal static string RequiredCost {
            get {
                return ResourceManager.GetString("RequiredCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل فیلد رشته تحصیلی الزامی می باشد..
        /// </summary>
        internal static string RequiredEducationBranch {
            get {
                return ResourceManager.GetString("RequiredEducationBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد مقطع تحصیلی را انتخاب نمایید..
        /// </summary>
        internal static string RequiredEducationLevel {
            get {
                return ResourceManager.GetString("RequiredEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً ایمیل خود را مشخص نمایید.
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ  پایان را انتخاب نمایید..
        /// </summary>
        internal static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً جنسیت خود را مشخص نمایید.
        /// </summary>
        internal static string RequiredGender {
            get {
                return ResourceManager.GetString("RequiredGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد خانه های ارتفاء را وارد نمایید..
        /// </summary>
        internal static string RequiredHeightBlocks {
            get {
                return ResourceManager.GetString("RequiredHeightBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شناسه را مشخص نمایید.
        /// </summary>
        internal static string RequiredID {
            get {
                return ResourceManager.GetString("RequiredID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر را انتخاب نمایید..
        /// </summary>
        internal static string RequiredImageFile {
            get {
                return ResourceManager.GetString("RequiredImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام خانوادگی خود را مشخص نمایید.
        /// </summary>
        internal static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان فاصله از چپ را وارد نمایید..
        /// </summary>
        internal static string RequiredLeftIndex {
            get {
                return ResourceManager.GetString("RequiredLeftIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام ارسالی شما خالی است، متنی برای پیامتان وارد نمایید..
        /// </summary>
        internal static string RequiredMessageText {
            get {
                return ResourceManager.GetString("RequiredMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام خود را مشخص نمایید.
        /// </summary>
        internal static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست ارسالی شما خالی است، جهت ارسال می بایست حداقل متن یا تصویری را وارد نمایید..
        /// </summary>
        internal static string RequiredPostTextOrPhoto {
            get {
                return ResourceManager.GetString("RequiredPostTextOrPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی اکانت مشخص نشده است.
        /// </summary>
        internal static string RequiredRegistrationCode {
            get {
                return ResourceManager.GetString("RequiredRegistrationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام مشخص نشده است.
        /// </summary>
        internal static string RequiredRegistrationDate {
            get {
                return ResourceManager.GetString("RequiredRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مهارت خود را وارد نمایید.
        /// </summary>
        internal static string RequiredSkillTitle {
            get {
                return ResourceManager.GetString("RequiredSkillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صفحه مقصد را وارد نمایید..
        /// </summary>
        internal static string RequiredTarget {
            get {
                return ResourceManager.GetString("RequiredTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان را وارد نمایید..
        /// </summary>
        internal static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان فاصله از بالا را وارد نمایید..
        /// </summary>
        internal static string RequiredTopIndex {
            get {
                return ResourceManager.GetString("RequiredTopIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد خانه های عرض را وارد نمایید..
        /// </summary>
        internal static string RequiredWidthBlocks {
            get {
                return ResourceManager.GetString("RequiredWidthBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالسازی حساب کاربری به ایمیل شما ارسال گردید، لطفاً به ایمیل خود مراجعه کرده و کد فعالسازی را از طریق فرم بالا ارسال نمایید و یا بر روی لینک فعالسازی حساب کاربری در ایمیل خود کلیک کنید، دقت کنید ممکن است ایمیل فعالسازی در پوشه spam قرار گرفته باشد.
        /// </summary>
        internal static string SendCodeSuccessful {
            get {
                return ResourceManager.GetString("SendCodeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً چند ثانیه صبر کنید و دوباره ارسال کنید..
        /// </summary>
        internal static string SpamGenralMessage {
            get {
                return ResourceManager.GetString("SpamGenralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به تازگی یک پست ارسال کرده اید، حداکثر 60 ثانیه بعد می توانید پست جدید ارسال نمایید..
        /// </summary>
        internal static string SpamPostMessage {
            get {
                return ResourceManager.GetString("SpamPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد درباره من، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthAboutMe {
            get {
                return ResourceManager.GetString("StringLengthAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح آلبوم، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthAlbumDesc {
            get {
                return ResourceManager.GetString("StringLengthAlbumDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام آلبوم، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthAlbumName {
            get {
                return ResourceManager.GetString("StringLengthAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام کاربری، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthAlias {
            get {
                return ResourceManager.GetString("StringLengthAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد خلق و خوی، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthBehavior {
            get {
                return ResourceManager.GetString("StringLengthBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن نظر حداکثر تعداد کاراکتر مجاز را رعایت نکرده است..
        /// </summary>
        internal static string StringLengthCommentText {
            get {
                return ResourceManager.GetString("StringLengthCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد درباره من، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthDescription {
            get {
                return ResourceManager.GetString("StringLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد تحصیلات، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthEducation {
            get {
                return ResourceManager.GetString("StringLengthEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد ایمیل، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthEmail {
            get {
                return ResourceManager.GetString("StringLengthEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد مد و ظاهر، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthFashion {
            get {
                return ResourceManager.GetString("StringLengthFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد کتاب های مورد علاقه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthFavoriteBooks {
            get {
                return ResourceManager.GetString("StringLengthFavoriteBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد فیلم های مورد علاقه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthFavoriteMovies {
            get {
                return ResourceManager.GetString("StringLengthFavoriteMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد موسیقی مورد علاقه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthFavoriteMusics {
            get {
                return ResourceManager.GetString("StringLengthFavoriteMusics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نقل قول های مورد علاقه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthFavoriteQuotes {
            get {
                return ResourceManager.GetString("StringLengthFavoriteQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاوز از حداکثر تعداد کاراکتر مجاز.
        /// </summary>
        internal static string StringLengthGeneral {
            get {
                return ResourceManager.GetString("StringLengthGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد سرگرمی ها و موضوعات مورد علاقه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthHobbies {
            get {
                return ResourceManager.GetString("StringLengthHobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد شناسه، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthID {
            get {
                return ResourceManager.GetString("StringLengthID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام خانوادگی، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthLastName {
            get {
                return ResourceManager.GetString("StringLengthLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthName {
            get {
                return ResourceManager.GetString("StringLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پست ارسالی از حداکثر طول مجاز تجاوز نموده است..
        /// </summary>
        internal static string StringLengthPostText {
            get {
                return ResourceManager.GetString("StringLengthPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد کد فعال سازی اکانت، حداکثر تعداد کاراکتر مجاز را رعایت نکرده است.
        /// </summary>
        internal static string StringLengthRegistrationCode {
            get {
                return ResourceManager.GetString("StringLengthRegistrationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر شما با موفقیت ارسال شد..
        /// </summary>
        internal static string SuccessfullyAddedComment {
            get {
                return ResourceManager.GetString("SuccessfullyAddedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلبوم تصاویر با موفقیت ایجاد شد.
        ///&lt;a href=&quot;/HomePage/Photos&quot;&gt;بازگشت به لیست آلبوم ها جهت ویرایش تصاویر.&lt;/a&gt;.
        /// </summary>
        internal static string SuccessfullyCreatedAlbum {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیـات حذف بـا موفقیت انجـام شد..
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت ذخیره شد..
        /// </summary>
        internal static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت ارسال گردید..
        /// </summary>
        internal static string SuccessfullySent {
            get {
                return ResourceManager.GetString("SuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل انتخابی با موفقیت ارسال شد، در زیر می توانید جزئیات مربوط به تصویر مورد نظرتان را ویرایش نمایید..
        /// </summary>
        internal static string SuccessfullyUploadedAlbumPhoto {
            get {
                return ResourceManager.GetString("SuccessfullyUploadedAlbumPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل انتخابی با موفقیت ارسال شد، در زیر می توانید تصویر کاور پروفایلتان را ویرایش نمایید..
        /// </summary>
        internal static string SuccessfullyUploadedProfieCover {
            get {
                return ResourceManager.GetString("SuccessfullyUploadedProfieCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، تصویر کاور پروفایل خود را از روی کامپیوتر شخصی خود انتخاب نمایید:.
        /// </summary>
        internal static string UploadCoverImageText {
            get {
                return ResourceManager.GetString("UploadCoverImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، تصویر نمایه پروفایل خود را از روی کامپیوتر شخصی خود انتخاب نمایید:.
        /// </summary>
        internal static string UploadProfileImageText {
            get {
                return ResourceManager.GetString("UploadProfileImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده قبلاً ثبت شده است.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با ایمیل وارد شده موجود نمی باشد، لطفاً مجدداً بررسی و اقدام نمایید..
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، این فایل ویدئویی در حال پردازش است، در حال حاضر پخش این فایل ممکن نیست.
        ///&lt;br /&gt;
        ///پردازش فایل ویدئویی بر اساس مدت زمان آن ممکن است از چند ثانیه تا چند دقیقه بطول بیانجامد..
        /// </summary>
        internal static string VideoNotProcessedYet {
            get {
                return ResourceManager.GetString("VideoNotProcessedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه صحیح نیست..
        /// </summary>
        internal static string WrongPasswordConfirm {
            get {
                return ResourceManager.GetString("WrongPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا در رابطه دوستی هستید..
        /// </summary>
        internal static string YouAreFriendsNow {
            get {
                return ResourceManager.GetString("YouAreFriendsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به اشتراک مواردی که متعلق به خودتان است نمی باشید..
        /// </summary>
        internal static string YouCantShareYourObjects {
            get {
                return ResourceManager.GetString("YouCantShareYourObjects", resourceCulture);
            }
        }
    }
}
