//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Texts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی جهت فعال سازی حساب کاربری خود، کد فعال سازی ارسال شده به ایمیل خود را از طریق فرم زیر وارد نمایید:
        ///            &lt;br /&gt;
        ///            (توجه: ممکن است ایمیل ارسال شده در پوشه spam ایمیل شما قرار گرفته باشد).
        /// </summary>
        internal static string ActivateAccountText {
            get {
                return ResourceManager.GetString("ActivateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می توانید تصاویری با حجم حداکثر 4 مگابایت برای هر تصویر را به آلبوم خود اضافه نمایید.
        ///&lt;br /&gt;
        ///تصاویر مجاز شامل پسوند های jpg, png و gif می باشد.
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///موارد ذیل مجاز نمی باشد و توسط مدیران حذف خواهند شد و درصورت تکرار، حساب کاربری شما حذف خواهد شد:
        ///&lt;ul&gt;
        ///&lt;li&gt;تصاویر حاوی صحنه های مبتذل&lt;/li&gt;
        ///&lt;li&gt;تصاویر حاوی مطالب نژادپرستانه یا توهین آمیز به گروه یا تفکر خاص&lt;/li&gt;
        ///&lt;li&gt;تصاویر حاوی مطالب سیاسی&lt;/li&gt;
        ///&lt;li&gt;تصاویر حاوی صحنه های خشونت آمیز&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string AlbumPhotosText {
            get {
                return ResourceManager.GetString("AlbumPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت تعیین ایمیل جایگزین، آگاه سازها و ایمیل های شبکه به این ایمیل ارسال خواهد شد..
        /// </summary>
        internal static string AlternativeEmailExplan {
            get {
                return ResourceManager.GetString("AlternativeEmailExplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران مسدود شده اجازه ارسال درخواست دوستی، ارسال پیام، آغاز چت، نوشتن روی دیوار شما و نوشتن کامنت روی مطالب شما را ندارند..
        /// </summary>
        internal static string BlockUsersText {
            get {
                return ResourceManager.GetString("BlockUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی تنها در صورتی تغییر گذرواژه اعمال خواهد شد که هر سه فیلد لازم پر شده باشند، در غیر این صورت گذرواژه تغییری نخواهد کرد..
        /// </summary>
        internal static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی در این مرحله با توجه به اینکه شما دارای حساب کاربری در شبکه اجتماعی vKurdistan نیستید، برای شما یک حساب کاربری بر اساس اطلاعات فیسبوک شما ایجاد شده و با حساب کاربری فیسبوکتان مرتبط خواهد شد.
        ///&lt;br /&gt;
        ///برای ورود به سایت می توانید هم از حساب کاربری فیسبوک و هم از حساب کاربری ایجاد شده در vKurdistan استفاده نمایید.
        ///&lt;br /&gt;
        ///توجه: گذرواژه حساب کاربری ایجاد شده به آدرس ایمیل اعلام شده از فیسبوک شما ارسال می شود..
        /// </summary>
        internal static string ConnectToFacebookAnonymousTextPart1 {
            get {
                return ResourceManager.GetString("ConnectToFacebookAnonymousTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال ارتباط حساب کاربری زیر با فیسبوک هستید..
        /// </summary>
        internal static string ConnectToFacebookAuthenticatedMemberTextPart1 {
            get {
                return ResourceManager.GetString("ConnectToFacebookAuthenticatedMemberTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه اجتماعی vKurdistan به شما این اطمینان را می دهد که هیچگونه اطلاعاتی بدون اجازه شما در فیسبوکتان به اشتراک گذاشته نخواهد شد همچنین این شبکه به هیچ عنوان به اطلاعات شخصی شما در فیسبوک دسترسی نخواهد داشت..
        /// </summary>
        internal static string ConnectToFacebookAuthenticatedMemberTextPart2 {
            get {
                return ResourceManager.GetString("ConnectToFacebookAuthenticatedMemberTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، شما بدون نیاز به ثبت نام در شبکه اجتماعی vKurdistan و با برقراری ارتباط با فیسبوک خود میتوانید از این شبکه اجتماعی استفاده نمایید. لطفاً به نکات زیر توجه بفرمایید:
        ///&lt;ul&gt;
        ///&lt;li&gt;شبکه اجتماعی vKurdistan به هیچ وجه پسورد فیسبوک شما را ذخیره نمی کند.&lt;/li&gt;
        ///&lt;li&gt;تنها اطلاعات مورد نیاز برای ثبت نام شما (نام، نام خانوادگی، ایمیل، جنسیت، تاریخ تولد و جنسیت) از فیسبوک گرفته می شود. &lt;/li&gt;
        ///&lt;li&gt;در صورتی که دارای حساب کاربری در شبکه اجتماعی vKurdistan هستید نیز می توانید حساب کاربری موجود خود را به حساب کاربر [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConnectToFacebookExplanation {
            get {
                return ResourceManager.GetString("ConnectToFacebookExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی چنانچه دارای حساب کاربری در vKurdistan هستید لطفاً جهت ارتباط این حساب کاربری با حساب کاربری فیسبوک خود از طریق فرم زیر وارد حساب خود شوید، در غیر این صورت یک حساب کاربری جدید در شبکه اجتماعی vKurdistan برای شما ایجاد خواهد شد.
        ///&lt;br /&gt;
        ///اگر دارای حساب کاربری در شبکه اجتماعی vKurdistan نیستید از این مرحله عبور کنید..
        /// </summary>
        internal static string ConnectToFacebookLoginExplanation {
            get {
                return ResourceManager.GetString("ConnectToFacebookLoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی چنانچه بدلیل حجم پیام ها یا درخواست ها و یا عدم تمایل به اشتراک پاره ای اطلاعات تصمیم به حذف حساب کاربریتان دارید، می توانید از قسمت &lt;a href=&quot;/HomePage/Privacy&quot;&gt;تنظیمات حریم خصوصی&lt;/a&gt; نسبت به عدم نمایش شما در نتایج جستجو و یا عدم پذیرش پیام یا درخواست دوستی اقدام نمایید، همچنین برای تمامی مطالب به اشتراک گذاشته شده قادر به تنظیم سطح دسترسی هستید..
        /// </summary>
        internal static string DeleteAccountText_Part1 {
            get {
                return ResourceManager.GetString("DeleteAccountText_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با فشردن دکمه &apos;حذف حساب کاربری&apos;، حساب کاربری شما برای حذف دائم برنامه ریزی خواهد شد، در این مدت اطلاعات شما به کاربران شبکه اجتماعی نمایش داده نخواهد شد، تا مدت 30 روز فرصت دارید که از حذف دائم حساب کاربریتان جلوگیری کنید، برای اینکار کافیست وارد حساب کاربریتان شوید..
        /// </summary>
        internal static string DeleteAccountText_Part2 {
            get {
                return ResourceManager.GetString("DeleteAccountText_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال حذف نظـر زیر هستید، آیا مطمئن هستید؟.
        /// </summary>
        internal static string DeleteCommentText {
            get {
                return ResourceManager.GetString("DeleteCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال حذف مکالمه خود با.
        /// </summary>
        internal static string DeleteConversationText_Part1 {
            get {
                return ResourceManager.GetString("DeleteConversationText_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هستید، آیا اطمینان دارید؟.
        /// </summary>
        internal static string DeleteConversationText_Part2 {
            get {
                return ResourceManager.GetString("DeleteConversationText_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال ویرایش نظر ارسالی زیر هستید، تغییرات را اعمال و ذخیره کنید:.
        /// </summary>
        internal static string EditCommentText {
            get {
                return ResourceManager.GetString("EditCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی ما از اطلاعات زیر جهت یافتن دوستان زمان مدرسه یا دانشگاهتان و یا معرفی افراد با مهارت های مشابه شما استفاده خواهیم کرد، لطفاً با دقت در تکمیل این داده ها ما را یاری نمایید..
        /// </summary>
        internal static string EducationsText {
            get {
                return ResourceManager.GetString("EducationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال به اشتراک گذاری مورد زیر در فیسبوک خود هستید، نحوه اشتراک گذاری را انتخاب نموده و تأیید نمایید.
        ///&lt;br /&gt;
        ///توجه: ممکن است پنجره ای از طرف فیسبوک باز شده و از شما درخواست ورود به فیسبوک و صدور مجوز نماید، در اینصورت، به اشتراک گذاری مورد فوق پس از ورود به فیسبوک به صورت خودکار ادامه خواهد یافت..
        /// </summary>
        internal static string FacebookShareDialogText {
            get {
                return ResourceManager.GetString("FacebookShareDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه شما خصوصی بوده و نمایش داده نخواهد شد، تنها در مواردی چون بازیابی رمز عبور، اطلاعرسانی ها و... استفاده خواهد شد..
        /// </summary>
        internal static string MobNumberText {
            get {
                return ResourceManager.GetString("MobNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما موارد انتخابی فوق از کاربران لیست سیاه را در صفحه پوشش خبری خود مشاهده نخواهید کرد..
        /// </summary>
        internal static string NewFeedUnwantedUsers {
            get {
                return ResourceManager.GetString("NewFeedUnwantedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات تصویر کاور پروفایل توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewChangeCover {
            get {
                return ResourceManager.GetString("NewsFeedViewChangeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات اطلاعات پروفایل توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewChangeInfo {
            get {
                return ResourceManager.GetString("NewsFeedViewChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات تصویر نمایه پروفایل توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewChangePP {
            get {
                return ResourceManager.GetString("NewsFeedViewChangePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات ارسال شده توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewComments {
            get {
                return ResourceManager.GetString("NewsFeedViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزوده شدن دوران تحصیلی جدید توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewEducations {
            get {
                return ResourceManager.GetString("NewsFeedViewEducations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب پسندیده شده توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewLikes {
            get {
                return ResourceManager.GetString("NewsFeedViewLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر به اشتراک گذاشته شده دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewPhotos {
            get {
                return ResourceManager.GetString("NewsFeedViewPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال های دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewPosts {
            get {
                return ResourceManager.GetString("NewsFeedViewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گذاری (بازنشر) های دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewShares {
            get {
                return ResourceManager.GetString("NewsFeedViewShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزوده شدن مهارت جدید توسط دوستان خود را در صفحه پوشش خبری خود مشاهده خواهید کرد..
        /// </summary>
        internal static string NewsFeedViewSkills {
            get {
                return ResourceManager.GetString("NewsFeedViewSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرهای ارسالی روی مطالب یا تصاویر شما از طریق ایمیل به اطلاع شما خواهد رسید..
        /// </summary>
        internal static string OnCommentText {
            get {
                return ResourceManager.GetString("OnCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام دریافت درخواست دوستی جدید، از طریق ایمیل به شما اطلاع داده خواهد شد..
        /// </summary>
        internal static string OnFriendshipRequestText {
            get {
                return ResourceManager.GetString("OnFriendshipRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسندهای مطالب یا تصاویر شما از طریق ایمیل به اطلاع شما خواهد رسید..
        /// </summary>
        internal static string OnLikeText {
            get {
                return ResourceManager.GetString("OnLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام دریافت پیام جدید، از طریق ایمیل به شما اطلاع داده خواهد شد..
        /// </summary>
        internal static string OnNewMessageText {
            get {
                return ResourceManager.GetString("OnNewMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گذاری مطالب یا تصاویر شما از طریق ایمیل به اطلاع شما خواهد رسید..
        /// </summary>
        internal static string OnShareText {
            get {
                return ResourceManager.GetString("OnShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست های ارسالی روی دیوار شما از طریق ایمیل به اطلاع شما خواهد رسید..
        /// </summary>
        internal static string OnWallPostText {
            get {
                return ResourceManager.GetString("OnWallPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی در صورتی که گذرواژه خود را فراموش کرده اید، می توانید از طریق فرم زیر نسبت به ارسال گذرواژه به ایمیل خود اقدام نمایید.
        ///&lt;br /&gt;
        ///(توجه: ممکن است ایمیل ارسال شده در پوشه spam ایمیل شما قرار بگیرد).
        /// </summary>
        internal static string PasswordRecoveryText {
            get {
                return ResourceManager.GetString("PasswordRecoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، شما در یک پست قادر به ارسال همزمان تصویر، ویدئو و صوت نمی باشید، در هر پست تنها می توانید تعدادی تصویر، یک فایل ویدوئویی و یا یک فایل صوتی را همراه با متن ارسال نمایید.
        ///&lt;br /&gt;
        ///توجه: در صورت تأیید، فایل های ارسال شده قبلی حذف و با فایل ارسالی جدید جایگزین خواهند شد..
        /// </summary>
        internal static string PostEditorWarningForFileTypes {
            get {
                return ResourceManager.GetString("PostEditorWarningForFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، شما اینجا می توانید تصویری را بعنوان تصویر کاور پروفایل خود ارسال و تنظیم نمایید.
        ///تصویر کاور تصویری است که در قسمت بالای صفحه پروفایل شما بصورت افقی نمایش داده می شود..
        /// </summary>
        internal static string ProfileCoverText {
            get {
                return ResourceManager.GetString("ProfileCoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال قطع رابطه دوستی زیر هستید، آیا مطمئن هستید؟.
        /// </summary>
        internal static string RemoveFriendText {
            get {
                return ResourceManager.GetString("RemoveFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همچنین می توانید بر روی لینک فعال سازی حساب کاربری در ایمیل خود کلیک کنید.
        ///            &lt;br /&gt;
        ///            چنانچه ایمیل حاوی کد فعالسازی برای شما ارسال نشده است می توانید از طریق فرم زیر نسبت به ارسال دوباره اقدام نمایید:.
        /// </summary>
        internal static string SendRegistrationCodeText {
            get {
                return ResourceManager.GetString("SendRegistrationCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در حال به اشتراک گذاری مورد زیر هستید، تنظیمات لازم را انجام داده و ذخیره نمایید:.
        /// </summary>
        internal static string ShareDialogText {
            get {
                return ResourceManager.GetString("ShareDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در کادر زیر عنوان هر یک از مهارتهای خود را بصورت جداگانه تایپ نموده و کلید Enter را بفشارید، در صورت وجود در لیست ظاهر شده آن را انتخاب نمایید..
        /// </summary>
        internal static string SkillsText {
            get {
                return ResourceManager.GetString("SkillsText", resourceCulture);
            }
        }
    }
}
